import type { PCPProviderManifest } from '@my-claudia/shared';

export const CLAUDE_MANIFEST: PCPProviderManifest = {
  id: 'claude',
  name: 'Claude',
  version: '1.0.0',
  apiVersion: 'pcp/v1',
  providerType: 'claude',
  runtime: 'cli',
  // Claude has native: TodoWrite ≈ update_todo_list, AskUserQuestion ≈ ask_user_form/request_approval,
  // plan mode ≈ enter/exit_plan_mode. Only push_file has no Claude equivalent.
  nativeInteractionTools: ['update_todo_list', 'ask_user_form', 'request_approval', 'enter_plan_mode', 'exit_plan_mode'],
  capabilities: [
    { id: 'chat.generate', supported: false, notes: 'Not implemented yet, planned for plugin API' },
    { id: 'chat.stream', supported: true, mode: 'native', reliability: 'strict' },
    { id: 'tool.call', supported: true, mode: 'native', reliability: 'strict' },
    { id: 'tool.inject', supported: true, mode: 'native', reliability: 'strict' },
    { id: 'interaction.form', supported: true, mode: 'bridged', reliability: 'strict' },
    { id: 'interaction.approval', supported: true, mode: 'bridged', reliability: 'strict' },
    { id: 'interaction.todo', supported: true, mode: 'bridged', reliability: 'strict' },
    { id: 'input.image', supported: true, mode: 'native', reliability: 'strict',
      limits: { attachmentModes: 'temp_file,file_path' } },
    { id: 'input.text_file', supported: true, mode: 'native', reliability: 'strict' },
    { id: 'input.binary_file', supported: true, mode: 'native', reliability: 'strict' },
    { id: 'permission.mode', supported: true, mode: 'native', reliability: 'strict' },
    { id: 'session.abort', supported: true, mode: 'native', reliability: 'strict' },
    { id: 'session.background_task', supported: true, mode: 'native', reliability: 'best_effort',
      notes: 'Background tasks initiated by model, not controllable by user' },
  ],
  permissionModeMap: {
    supervised: 'default',
    auto_edit: 'acceptEdits',
    autonomous: 'bypassPermissions',
    plan_only: 'plan',
  },
};

export const OPENCODE_MANIFEST: PCPProviderManifest = {
  id: 'opencode',
  name: 'OpenCode',
  version: '1.0.0',
  apiVersion: 'pcp/v1',
  providerType: 'opencode',
  runtime: 'cli',
  capabilities: [
    { id: 'chat.generate', supported: false },
    { id: 'chat.stream', supported: true, mode: 'native', reliability: 'strict' },
    { id: 'tool.call', supported: true, mode: 'native', reliability: 'strict' },
    { id: 'tool.inject', supported: true, mode: 'native', reliability: 'strict' },
    { id: 'interaction.form', supported: true, mode: 'bridged', reliability: 'best_effort' },
    { id: 'interaction.approval', supported: true, mode: 'bridged', reliability: 'best_effort' },
    { id: 'interaction.todo', supported: true, mode: 'bridged', reliability: 'best_effort' },
    { id: 'input.image', supported: true, mode: 'native', reliability: 'strict',
      limits: { attachmentModes: 'data_uri' } },
    { id: 'input.text_file', supported: true, mode: 'native', reliability: 'strict' },
    { id: 'input.binary_file', supported: true, mode: 'native', reliability: 'strict' },
    { id: 'permission.mode', supported: true, mode: 'native', reliability: 'strict' },
    { id: 'session.abort', supported: true, mode: 'native', reliability: 'strict' },
    { id: 'session.background_task', supported: false },
  ],
  permissionModeMap: {
    supervised: 'default',
    autonomous: 'yolo',
    plan_only: 'plan',
  },
};

export const CODEX_MANIFEST: PCPProviderManifest = {
  id: 'codex',
  name: 'Codex',
  version: '1.0.0',
  apiVersion: 'pcp/v1',
  providerType: 'codex',
  runtime: 'cli',
  capabilities: [
    { id: 'chat.generate', supported: false },
    { id: 'chat.stream', supported: true, mode: 'native', reliability: 'strict' },
    { id: 'tool.call', supported: true, mode: 'native', reliability: 'strict' },
    { id: 'tool.inject', supported: true, mode: 'native', reliability: 'strict' },
    { id: 'interaction.form', supported: true, mode: 'bridged', reliability: 'best_effort' },
    { id: 'interaction.approval', supported: true, mode: 'bridged', reliability: 'best_effort' },
    { id: 'interaction.todo', supported: true, mode: 'bridged', reliability: 'best_effort' },
    { id: 'input.image', supported: true, mode: 'native', reliability: 'strict',
      limits: { attachmentModes: 'file_path' } },
    { id: 'input.text_file', supported: true, mode: 'native', reliability: 'strict' },
    { id: 'input.binary_file', supported: true, mode: 'native', reliability: 'strict' },
    { id: 'permission.mode', supported: true, mode: 'native', reliability: 'strict' },
    { id: 'session.abort', supported: true, mode: 'native', reliability: 'strict' },
    { id: 'session.background_task', supported: false },
  ],
  permissionModeMap: {
    supervised: 'default',
    auto_edit: 'acceptEdits',
    autonomous: 'bypassPermissions',
    plan_only: 'plan',
  },
};

export const CURSOR_MANIFEST: PCPProviderManifest = {
  id: 'cursor',
  name: 'Cursor',
  version: '1.0.0',
  apiVersion: 'pcp/v1',
  providerType: 'cursor',
  runtime: 'cli',
  capabilities: [
    { id: 'chat.generate', supported: false },
    { id: 'chat.stream', supported: true, mode: 'native', reliability: 'best_effort' },
    { id: 'tool.call', supported: true, mode: 'native', reliability: 'best_effort' },
    { id: 'tool.inject', supported: true, mode: 'bridged', reliability: 'best_effort',
      notes: 'Via .cursor/mcp.json injection' },
    { id: 'interaction.form', supported: true, mode: 'bridged', reliability: 'best_effort' },
    { id: 'interaction.approval', supported: true, mode: 'bridged', reliability: 'best_effort' },
    { id: 'interaction.todo', supported: true, mode: 'bridged', reliability: 'best_effort' },
    { id: 'input.image', supported: true, mode: 'native', reliability: 'strict',
      limits: { attachmentModes: 'file_path' } },
    { id: 'input.text_file', supported: true, mode: 'native', reliability: 'strict' },
    { id: 'input.binary_file', supported: true, mode: 'native', reliability: 'strict' },
    { id: 'permission.mode', supported: true, mode: 'native', reliability: 'strict' },
    { id: 'session.abort', supported: true, mode: 'native', reliability: 'strict' },
    { id: 'session.background_task', supported: false },
  ],
  permissionModeMap: {
    supervised: 'default',
    plan_only: 'plan',
  },
};

export const KIMI_MANIFEST: PCPProviderManifest = {
  id: 'kimi',
  name: 'Kimi',
  version: '1.0.0',
  apiVersion: 'pcp/v1',
  providerType: 'kimi',
  runtime: 'cli',
  capabilities: [
    { id: 'chat.generate', supported: false },
    { id: 'chat.stream', supported: true, mode: 'native', reliability: 'best_effort' },
    { id: 'tool.call', supported: true, mode: 'native', reliability: 'best_effort' },
    { id: 'tool.inject', supported: true, mode: 'bridged', reliability: 'best_effort' },
    { id: 'interaction.form', supported: true, mode: 'bridged', reliability: 'best_effort' },
    { id: 'interaction.approval', supported: true, mode: 'bridged', reliability: 'best_effort' },
    { id: 'interaction.todo', supported: true, mode: 'bridged', reliability: 'best_effort' },
    { id: 'input.image', supported: true, mode: 'native', reliability: 'strict',
      limits: { attachmentModes: 'file_path' } },
    { id: 'input.text_file', supported: true, mode: 'native', reliability: 'strict' },
    { id: 'input.binary_file', supported: true, mode: 'native', reliability: 'strict' },
    { id: 'permission.mode', supported: true, mode: 'native', reliability: 'strict' },
    { id: 'session.abort', supported: true, mode: 'native', reliability: 'strict' },
    { id: 'session.background_task', supported: false },
  ],
  permissionModeMap: {
    supervised: 'default',
    autonomous: 'yolo',
    plan_only: 'plan',
  },
};

/** All built-in provider manifests */
export const BUILTIN_MANIFESTS: Record<string, PCPProviderManifest> = {
  claude: CLAUDE_MANIFEST,
  opencode: OPENCODE_MANIFEST,
  codex: CODEX_MANIFEST,
  cursor: CURSOR_MANIFEST,
  kimi: KIMI_MANIFEST,
};
