#!/usr/bin/env bash
# Centralized version management for all platforms
#
# Usage:
#   ./scripts/version-bump.sh --platform android              # show version (no changes)
#   ./scripts/version-bump.sh --platform android --bump        # increment build + update files
#   ./scripts/version-bump.sh --platform android --set-build 42  # set specific build number
#   ./scripts/version-bump.sh --platform android --set-build 42 --dev-suffix  # dev build
#
# version.json holds only { "major": N, "minor": N }
# Build number is derived from git tags: build-{major}.{minor}-{N}
#
# Platform codes: android=1, macos=2, linux=3, windows=4
# Version format: {major}.{minor}.{platform_code}{build_number:02d}
# Example: 0.1.142 = Android, build #42
set -euo pipefail
cd "$(dirname "$0")/.."

# --- Parse args ---
PLATFORM=""
BUMP=false
SET_BUILD=""
DEV_SUFFIX=false

while [[ $# -gt 0 ]]; do
  case "$1" in
    --platform) PLATFORM="$2"; shift 2 ;;
    --bump) BUMP=true; shift ;;
    --set-build) SET_BUILD="$2"; shift 2 ;;
    --dev-suffix) DEV_SUFFIX=true; shift ;;
    *) echo "Unknown arg: $1"; exit 1 ;;
  esac
done

if [ -z "$PLATFORM" ]; then
  echo "ERROR: --platform is required (android|macos|linux|windows)"
  exit 1
fi

# --- Platform code mapping ---
case "$PLATFORM" in
  android) PLATFORM_CODE=1 ;;
  macos)   PLATFORM_CODE=2 ;;
  linux)   PLATFORM_CODE=3 ;;
  windows) PLATFORM_CODE=4 ;;
  *) echo "ERROR: Unknown platform '$PLATFORM'. Use: android|macos|linux|windows"; exit 1 ;;
esac

# --- Read version.json (only major + minor) ---
VERSION_FILE="version.json"
if [ ! -f "$VERSION_FILE" ]; then
  echo "ERROR: $VERSION_FILE not found"
  exit 1
fi

MAJOR=$(python3 -c "import json; print(json.load(open('$VERSION_FILE'))['major'])")
MINOR=$(python3 -c "import json; print(json.load(open('$VERSION_FILE'))['minor'])")

# --- Get build number from git tags ---
LATEST_TAG=$(git tag -l "build-${MAJOR}.${MINOR}-*" --sort=-version:refname | head -1)
if [ -n "$LATEST_TAG" ]; then
  BUILD=$(echo "$LATEST_TAG" | sed "s/build-${MAJOR}.${MINOR}-//")
else
  BUILD=0
fi

# --- Bump or set build ---
if [ "$BUMP" = true ]; then
  BUILD=$((BUILD + 1))
  echo "Build number bumped to $BUILD"
elif [ -n "$SET_BUILD" ]; then
  BUILD="$SET_BUILD"
  echo "Build number set to $BUILD"
fi

# --- Compute version strings ---
PATCH=$(printf "%d%02d" "$PLATFORM_CODE" "$BUILD")
VERSION="${MAJOR}.${MINOR}.${PATCH}"
if [ "$DEV_SUFFIX" = true ]; then
  VERSION="${VERSION}-dev"
fi
# versionCode is always a plain integer (Android requires this)
VERSION_CODE="$PATCH"

echo ""
echo "  Platform:     $PLATFORM (code=$PLATFORM_CODE)"
echo "  Build:        $BUILD"
echo "  Version:      $VERSION"
echo "  VersionCode:  $VERSION_CODE"

# --- If not bumping/setting, just display ---
if [ "$BUMP" = false ] && [ -z "$SET_BUILD" ]; then
  exit 0
fi

# --- Update platform version files ---
echo ""
echo "Updating version files..."

# 1. tauri.conf.json
TAURI_CONF="apps/desktop/src-tauri/tauri.conf.json"
if [ -f "$TAURI_CONF" ]; then
  python3 -c "
import json
with open('$TAURI_CONF', 'r') as f:
    d = json.load(f)
d['version'] = '$VERSION'
with open('$TAURI_CONF', 'w') as f:
    json.dump(d, f, indent=2)
    f.write('\n')
"
  echo "  [OK] $TAURI_CONF → $VERSION"
fi

# 2. Cargo.toml
CARGO_TOML="apps/desktop/src-tauri/Cargo.toml"
if [ -f "$CARGO_TOML" ]; then
  python3 -c "
import re
with open('$CARGO_TOML', 'r') as f:
    content = f.read()
content = re.sub(r'(^version\s*=\s*\")([^\"]+)(\")', r'\g<1>$VERSION\3', content, count=1, flags=re.MULTILINE)
with open('$CARGO_TOML', 'w') as f:
    f.write(content)
"
  echo "  [OK] $CARGO_TOML → $VERSION"
fi

# 3. Root package.json
ROOT_PKG="package.json"
if [ -f "$ROOT_PKG" ]; then
  python3 -c "
import json
with open('$ROOT_PKG', 'r') as f:
    d = json.load(f)
d['version'] = '$VERSION'
with open('$ROOT_PKG', 'w') as f:
    json.dump(d, f, indent=2)
    f.write('\n')
"
  echo "  [OK] $ROOT_PKG → $VERSION"
fi

# 4. Desktop package.json
DESKTOP_PKG="apps/desktop/package.json"
if [ -f "$DESKTOP_PKG" ]; then
  python3 -c "
import json
with open('$DESKTOP_PKG', 'r') as f:
    d = json.load(f)
d['version'] = '$VERSION'
with open('$DESKTOP_PKG', 'w') as f:
    json.dump(d, f, indent=2)
    f.write('\n')
"
  echo "  [OK] $DESKTOP_PKG → $VERSION"
fi

# 5. Android tauri.properties (only for android platform)
TAURI_PROPS="apps/desktop/src-tauri/gen/android/app/tauri.properties"
if [ -f "$TAURI_PROPS" ]; then
  cat > "$TAURI_PROPS" <<EOF
// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
tauri.android.versionName=$VERSION
tauri.android.versionCode=$VERSION_CODE
EOF
  echo "  [OK] $TAURI_PROPS → versionName=$VERSION, versionCode=$VERSION_CODE"
fi

echo ""
echo "=== Version updated: $VERSION ($PLATFORM) ==="
